# Generated by Django 5.0 on 2024-01-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_date', models.DateField(blank=True, null=True)),
                ('approval_number', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('transmission_date', models.DateField(blank=True, null=True)),
                ('supplier_registration_number', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_branch_number', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_representative_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_address', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient_registration_number', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient_branch_number', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient_business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient_representative_name', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient_address', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('supply_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('electronic_invoice_classification', models.CharField(blank=True, max_length=255, null=True)),
                ('electronic_invoice_type', models.CharField(blank=True, max_length=255, null=True)),
                ('issuance_type', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('receipt_billing_division', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('recipient_email1', models.EmailField(blank=True, max_length=254, null=True)),
                ('recipient_email2', models.EmailField(blank=True, max_length=254, null=True)),
                ('item_date', models.DateField(blank=True, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_specification', models.CharField(blank=True, max_length=255, null=True)),
                ('item_quantity', models.FloatField(blank=True, null=True)),
                ('item_unit_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('item_supply_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('item_tax_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('item_remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
